### PR TITLE
 theme tweaks

### PR DESCRIPTION
**Pull request by lixonic**
screen

### CODE REVIEW

**Comment by vipulnsward** [comment]
@lixonic can you fix link colors?
Neeraj was saying the links aren't prominent.

**Comment by lixonic** [comment]
@vipulnsward  can you review the changes ?

**Comment by vipulnsward** [comment]
@lixonic Please squash the commits

**Comment by vipulnsward** [comment]
Can you post screenshot here?

**Comment by lixonic** [comment]
@vipulnsward  these tweaks can be ignored

**Pull request closed without merging**
